# Generated by Django 5.0.14 on 2026-09-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Verified', 'Verified'), ('Needs Review', 'Needs Review')], default='Pending', max_length=50),
        ),
    ]
