# Generated by Django 5.0.14 on 2026-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('customer', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('avg_delay_days', models.IntegerField(default=0)),
                ('payment_behavior', models.CharField(default='Stable Terms Adherence', max_length=100)),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('default_rate_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_reliability_score', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
